### ISSUE TITLE
Plugin doesn't save player XP like it does Inventory.

### ISSUE THREAD

**Issue by stronger108** [Plajer-Lair/MurderMystery#15]
Hello! My players and I noticed our XP's get wiped at the end (or beginning?) of a match because of the countdown timer that is also the bossbar. My server is a server just for close friends and we don't have any bungee stuff like lobbys and worlds and such so they join the matches in survival with actual item and XP. Even just an option to turn off the XP timer would be awesome if you didn't want to store the player XP since the timer is already in the boss bar.

Thanks!

**Comment by Tigerpanzer02** [comment]
Hey @stronger108,

sry about this Plugin issue. We already fixed it. The new spigot version will include the update. If you need it as fast as possible contact us on discord and create a ticket.
